### ISSUE TITLE
notifications are showing but no sound

### ISSUE THREAD

**Issue by eadmaster** [dimonomid/my-udev-notify#7]
The notifications are showing correctly on my KDE desktop, but i hear no sound.

I've tried:
 - invoking ` /usr/bin/play -q "$soundfile" &` from the terminal, and it plays the configured sound fine.
 - setting `use_espeak == true`

My OS: `Linux version 4.15.0-50-generic (buildd@lcy01-amd64-013) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019`

In the past i had a similar issue with system-triggered audio notifications and it was an permissions-related problem...

**Comment by dimonomid** [comment]
Got the same problem after upgrading my OS. Should be fixed by https://github.com/dimonomid/my-udev-notify/commit/e4eecf1493abb78107a0603adad12cef127058a7

**Comment by eadmaster** [comment]
I confirm sounds are now  playing correctly in my system.
